### ISSUE TITLE
Unable to Publish Container to Maven Repository

### ISSUE THREAD

**Issue by noelob** [palantir/gradle-docker#222]
I'm using Gradle 5.1.1 for my build with plugin verision 0.21.0 and, when trying to publish docker images to Maven local, an error occurs:

```
./gradlew publishDockerPublicationToMavenLocal -S

FAILURE: Build failed with an exception.

* What went wrong:
com.palantir.gradle.docker.DockerComponent$RuntimeUsageContext.getGlobalExcludes()Ljava/util/Set;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.AbstractMethodError: com.palantir.gradle.docker.DockerComponent$RuntimeUsageContext.getGlobalExcludes()Ljava/util/Set;
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.populateFromComponent(DefaultMavenPublication.java:246)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.getPublishableArtifacts(DefaultMavenPublication.java:356)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication_Decorated.getPublishableArtifacts(Unknown Source)
        at org.gradle.api.publish.maven.tasks.AbstractPublishToMaven$1.call(AbstractPublishToMaven.java:46)
        at org.gradle.api.publish.maven.tasks.AbstractPublishToMaven$1.call(AbstractPublishToMaven.java:43)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
```

Building the image using `./gradlew docker` works fine.

My build script contains the publication config as follows:
```
publishing {
  publications {
    docker(MavenPublication) {
      from components.docker
      artifactId project.name + "-docker"
    }
  }
}
```

Seems like the plugin is built against an internal interface (UsageContext) which has changed in recent version of Gradle and broken the plugin. Is there a workaround for this?

**Comment by pkoenig10** [comment]
We just need to merge this PR:
https://github.com/palantir/gradle-docker/pull/204

I started working on this a while ago but hit some issues with dependency resolution.

**Comment by AnakinPt** [comment]
I have this error now, starting from the last couple of days. 
Is there anything I can do to minimize this?
