### ISSUE TITLE
Gradle-docker within gradle image

### ISSUE THREAD

**Issue by 2020testuser** [palantir/gradle-docker#352]
## What happened?
Hi, I'm using Gradle docker image (pulled from docker.com). I'm building my spring boot application using Gradle-docker plugin and the plugin creates the application docker image.
However, when I build the application using gradle docker image, I get an error.

Docker command
docker run --rm  -u "$(id -u):$(id -g)" -v "${HOME}:/user"  -v "$PWD":/home/myapp -w /home/myapp <company docker repo>/myapp/gradle:4.5  gradle  --gradle-user-home c: -s -x test  myapp:docker
Error Msg:
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'docker'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
	... 4 more
Caused by: java.io.IOException: Cannot run program "docker" (in directory "/home/myapp/docker"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)

## What did you want to happen?
I want the image to be build successfully when I run my docker command.

**Comment by curtis2point0** [comment]
I'm also struggling with this issue on a newly created gradle multi-project.

I've found discussion here
https://github.com/palantir/gradle-docker/issues/162
and here
https://github.com/palantir/gradle-docker/pull/172

I've tried nearly everything I could find that made a modicum of sense to no avail. 

I don't know if it's relevant, however when I tried making the app/build/docker directory it (and its contents) get deleted during the docker task.

**Comment by chairbender** [comment]
I found I needed to manually stop all gradle daemons with `./gradlew --stop` to fix this when it happens (and then try the task again).

**Comment by janhoy** [comment]
> I found I needed to manually stop all gradle daemons with `./gradlew --stop` to fix this when it happens (and then try the task again).

Thanks a lot, this helped me as well. Hopefully this will not happen in CI pipelines, or perhaps a workaround is to run with `--no-daemon`?
