### ISSUE TITLE
Support gradle 8.12

### ISSUE THREAD

**Issue by thaarbach** [palantir/gradle-docker#801]
## Not compatible to gradle 8.12

```
* What went wrong:
A problem occurred evaluating project ':shop-hama'.
> Failed to apply plugin 'com.palantir.docker'.
   > Could not create plugin of type 'PalantirDockerPlugin'.
      > Could not generate a decorated class for type PalantirDockerPlugin.
         > org/gradle/api/internal/attributes/ImmutableAttributesFactory

```

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.palantir.docker'.
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:176)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:148)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:162)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:44)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:99)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:185)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
	at org.gradle.api.internal.project.DefaultProject.apply(DefaultProject.java:1556)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_3mkpqli4o5yi8tjjaaktejpe.run(/builds/jstage/jstage-shop/shop-hama/build.gradle:9)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 158 more
Caused by: org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'PalantirDockerPlugin'.
	at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:85)
	at org.gradle.api.internal.plugins.DefaultPluginManager.producePluginInstance(DefaultPluginManager.java:209)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:185)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
	... 169 more
Caused by: org.gradle.internal.instantiation.ClassGenerationException: Could not generate a decorated class for type PalantirDockerPlugin.
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:260)
	at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:130)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generate(AbstractClassGenerator.java:190)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator.generate(AsmBackedClassGenerator.java:123)
	at org.gradle.internal.instantiation.generator.Jsr330ConstructorSelector.lambda$forType$0(Jsr330ConstructorSelector.java:56)
	at org.gradle.cache.Cache.lambda$get$0(Cache.java:31)
	at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:130)
	at org.gradle.cache.Cache.get(Cache.java:31)
	at org.gradle.internal.instantiation.generator.Jsr330ConstructorSelector.forType(Jsr330ConstructorSelector.java:53)
	at org.gradle.internal.instantiation.generator.Jsr330ConstructorSelector.forParams(Jsr330ConstructorSelector.java:48)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:59)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:53)
	at org.gradle.api.internal.plugins.PluginInstantiator.newInstance(PluginInstantiator.java:49)
	at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:83)
	... 183 more
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/attributes/ImmutableAttributesFactory
	at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:88)
	at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
	at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:289)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:229)
	... 196 more
Caused by: java.lang.ClassNotFoundException: org.gradle.api.internal.attributes.ImmutableAttributesFactory
	at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
	... 201 more
```

Rename `ImmutableAttributesFactory` to `AttributesFactory` should be solve the Problem

**Comment by matt-lachman-trss** [comment]
I'm running into this just now, trying to upgrade a project to the latest 8.X gradle version.

**Comment by Zordid** [comment]
Also facing the same issue... :(

**Comment by Zordid** [comment]
Is anybody still caring for this plugin? Please.... can someone fix this issue? The other question would be: how do you build docker images from Gradle builds without this plugin? Thanks!

**Comment by axiomatics-andreas** [comment]
+1

**Comment by thaarbach** [comment]
> Is anybody still caring for this plugin? Please.... can someone fix this issue? The other question would be: how do you build docker images from Gradle builds without this plugin? Thanks!

@Zordid in some project we use google jib 

I will create PR, but at the moment i am struggle with the docker compose part / plugin. The test fails on my local machine and i don't why.

**Comment by atlacyp** [comment]
For some reason this does not appear to have been published

**Comment by Zordid** [comment]
This release 0.37.0 is missing on Gradle repo... cannot use it. :-(
